import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  FileText,
  Clock,
  CheckCircle,
  XCircle,
  ArrowRightCircle,
  Loader2,
  RefreshCw,
  Plus,
  Trash2,
} from 'lucide-react';

interface ClientLite {
  id: string;
  name: string;
  email: string | null;
}

interface Estimate {
  id: string;
  tenantId: string;
  clientId: string;
  client?: ClientLite | null;
  amountCents: number;
  description: string;
  status: 'pending' | 'approved' | 'declined' | 'expired' | 'converted';
  validUntil: string;
  convertedInvoiceId: string | null;
  createdAt: string;
  updatedAt: string;
  // Number is generated by the backend on read (not persisted).
  number?: string;
}

const STATUSES: Array<Estimate['status'] | 'all'> = ['all', 'pending', 'approved', 'declined', 'expired', 'converted'];

const STATUS_CONFIG: Record<Estimate['status'], { label: string; bg: string; text: string; icon: React.ReactNode }> = {
  pending: { label: 'Pending', bg: 'bg-amber-100', text: 'text-amber-700', icon: <Clock className="w-3 h-3" /> },
  approved: { label: 'Approved', bg: 'bg-green-100', text: 'text-green-700', icon: <CheckCircle className="w-3 h-3" /> },
  declined: { label: 'Declined', bg: 'bg-red-100', text: 'text-red-700', icon: <XCircle className="w-3 h-3" /> },
  expired: { label: 'Expired', bg: 'bg-gray-100', text: 'text-gray-500', icon: <Clock className="w-3 h-3" /> },
  converted: { label: 'Converted', bg: 'bg-blue-100', text: 'text-blue-700', icon: <ArrowRightCircle className="w-3 h-3" /> },
};

function formatCurrency(cents: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
}

function formatDate(d: string) {
  return new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

// Mirrors the backend's formatEstimateNumber — kept defensively so the UI
// renders even when the API hasn't injected `number` yet.
function fallbackNumber(est: Estimate): string {
  const year = new Date(est.createdAt).getUTCFullYear();
  const tail = (est.id || '').replace(/-/g, '').slice(-4).toUpperCase();
  return `EST-${year}-${tail || '0000'}`;
}

export const EstimatesPage: React.FC = () => {
  const [estimates, setEstimates] = useState<Estimate[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [filter, setFilter] = useState<Estimate['status'] | 'all'>('all');

  const fetchEstimates = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/v1/agentbook-invoice/estimates');
      if (!res.ok) throw new Error('Failed to fetch estimates');
      const json = await res.json();
      const rows: Estimate[] = Array.isArray(json) ? json : json.data ?? json.estimates ?? [];
      setEstimates(rows);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchEstimates();
  }, [fetchEstimates]);

  const visible = useMemo(
    () => (filter === 'all' ? estimates : estimates.filter((e) => e.status === filter)),
    [estimates, filter],
  );

  const callAction = async (id: string, path: string, method: 'POST' | 'DELETE' = 'POST') => {
    setBusyId(id);
    try {
      const res = await fetch(`/api/v1/agentbook-invoice/estimates/${id}${path}`, { method });
      if (!res.ok) {
        const j = await res.json().catch(() => ({}));
        throw new Error(j.error || `Request failed (${res.status})`);
      }
      await fetchEstimates();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusyId(null);
    }
  };

  const handleApprove = (id: string) => callAction(id, '/accept');
  const handleDecline = (id: string) => callAction(id, '/decline');
  const handleConvert = (id: string) => callAction(id, '/convert');
  const handleDelete = (id: string) => callAction(id, '', 'DELETE');

  return (
    <div className="p-4 sm:p-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>
            Estimates
          </h1>
          <p className="text-sm mt-1" style={{ color: 'var(--text-secondary)' }}>
            Create estimates and convert them to invoices
          </p>
        </div>
        <button
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium text-white transition-colors"
          style={{ backgroundColor: 'var(--accent-emerald, #10b981)' }}
        >
          <Plus className="w-4 h-4" />
          New Estimate
        </button>
      </div>

      {/* Status filters */}
      <div className="flex flex-wrap gap-2 mb-4">
        {STATUSES.map((s) => (
          <button
            key={s}
            onClick={() => setFilter(s)}
            className={`px-3 py-1.5 rounded-full text-xs font-medium border transition-colors ${
              filter === s
                ? 'bg-emerald-50 border-emerald-200 text-emerald-700'
                : 'bg-white border-gray-200 text-gray-600 hover:bg-gray-50'
            }`}
          >
            {s === 'all' ? 'All' : STATUS_CONFIG[s].label}
          </button>
        ))}
      </div>

      {/* Content */}
      {loading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-6 h-6 animate-spin" style={{ color: 'var(--accent-emerald)' }} />
        </div>
      ) : error ? (
        <div className="text-center py-20">
          <p className="text-red-500 mb-3">{error}</p>
          <button
            onClick={fetchEstimates}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium border hover:bg-gray-50"
          >
            <RefreshCw className="w-4 h-4" /> Retry
          </button>
        </div>
      ) : visible.length === 0 ? (
        <div className="text-center py-20" style={{ color: 'var(--text-secondary)' }}>
          <FileText className="w-10 h-10 mx-auto mb-3 opacity-40" />
          <p className="font-medium">No estimates yet</p>
          <p className="text-sm mt-1">Create your first estimate to get started.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {visible.map((est) => {
            const cfg = STATUS_CONFIG[est.status] ?? STATUS_CONFIG.pending;
            const number = est.number || fallbackNumber(est);
            const clientName = est.client?.name || '(unknown client)';
            const isBusy = busyId === est.id;
            return (
              <div
                key={est.id}
                className="rounded-xl p-4 border border-border bg-card transition-shadow hover:shadow-md"
              >
                <div className="flex flex-col sm:flex-row sm:items-center gap-3">
                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="font-semibold text-sm text-foreground">
                        {number}
                      </span>
                      <span
                        className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium ${cfg.bg} ${cfg.text}`}
                      >
                        {cfg.icon}
                        {cfg.label}
                      </span>
                    </div>
                    <p className="text-sm text-muted-foreground">{clientName}</p>
                    <p className="text-xs mt-1" style={{ color: 'var(--text-secondary)' }}>
                      {est.description} &middot; Created {formatDate(est.createdAt)} &middot; Valid until{' '}
                      {formatDate(est.validUntil)}
                    </p>
                  </div>

                  {/* Amount + actions */}
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-bold text-base mr-1" style={{ color: 'var(--text-primary)' }}>
                      {formatCurrency(est.amountCents)}
                    </span>

                    {est.status === 'pending' && (
                      <>
                        <button
                          onClick={() => handleApprove(est.id)}
                          disabled={isBusy}
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border bg-white hover:bg-emerald-50 disabled:opacity-50"
                        >
                          {isBusy ? <Loader2 className="w-3 h-3 animate-spin" /> : <CheckCircle className="w-3 h-3" />}
                          Approve
                        </button>
                        <button
                          onClick={() => handleDecline(est.id)}
                          disabled={isBusy}
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border bg-white hover:bg-red-50 disabled:opacity-50"
                        >
                          <XCircle className="w-3 h-3" /> Decline
                        </button>
                      </>
                    )}

                    {(est.status === 'approved' || est.status === 'pending') && (
                      <button
                        onClick={() => handleConvert(est.id)}
                        disabled={isBusy}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-white transition-colors disabled:opacity-50"
                        style={{ backgroundColor: 'var(--accent-emerald, #10b981)' }}
                      >
                        {isBusy ? (
                          <Loader2 className="w-3 h-3 animate-spin" />
                        ) : (
                          <ArrowRightCircle className="w-3 h-3" />
                        )}
                        Convert to Invoice
                      </button>
                    )}

                    {(est.status === 'pending' || est.status === 'declined' || est.status === 'expired') && (
                      <button
                        onClick={() => handleDelete(est.id)}
                        disabled={isBusy}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border bg-white hover:bg-red-50 disabled:opacity-50"
                        title="Delete estimate"
                      >
                        <Trash2 className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default EstimatesPage;
