import type { IProviderAdapter, DestroyResult } from './IProviderAdapter.js';
import type {
  GpuOption,
  DeployConfig,
  UpdateConfig,
  ProviderDeployment,
  ProviderStatus,
  HealthResult,
  ProviderApiConfig,
} from '../types/index.js';
import { authenticatedProviderFetch } from '../lib/providerFetch.js';

const SSH_BRIDGE_URL = process.env.SSH_BRIDGE_URL || 'http://localhost:2222';

/**
 * SSH-based adapter for multi-container Docker Compose deployments.
 *
 * Unlike SshBridgeAdapter (single container via `docker run`), this adapter:
 * - Writes a docker-compose.yml to the remote host
 * - Runs `docker compose up -d` to start all services
 * - Destroys via `docker compose down`
 *
 * Used by the livepeer-inference template to deploy go-livepeer + adapter + backend
 * as a single compose stack.
 *
 * The compose YAML is passed via config.artifactConfig.composeYaml (generated by
 * LivepeerComposeBuilder).
 */
export class SshComposeAdapter implements IProviderAdapter {
  readonly slug = 'ssh-compose';
  readonly displayName = 'SSH Compose (Multi-Container)';
  readonly mode = 'ssh-bridge' as const;
  readonly icon = '🐳';
  readonly description = 'Deploy multi-container Docker Compose stacks to machines via SSH.';
  readonly authMethod = 'ssh-key';
  readonly apiConfig: ProviderApiConfig = {
    upstreamBaseUrl: SSH_BRIDGE_URL,
    authType: 'none',
    secretNames: ['ssh-key'],
    healthCheckPath: '/healthz',
  };

  async getGpuOptions(): Promise<GpuOption[]> {
    return [
      { id: 'CPU', name: 'CPU Only (no GPU needed)', vramGb: 0, available: true },
      { id: 'NVIDIA A100 80GB', name: 'NVIDIA A100 80GB', vramGb: 80, available: true },
      { id: 'NVIDIA A100 40GB', name: 'NVIDIA A100 40GB', vramGb: 40, available: true },
      { id: 'NVIDIA H100 80GB', name: 'NVIDIA H100 80GB', vramGb: 80, available: true },
      { id: 'NVIDIA H100 SXM', name: 'NVIDIA H100 SXM', vramGb: 80, available: true },
      { id: 'NVIDIA L40S', name: 'NVIDIA L40S', vramGb: 48, available: true },
      { id: 'NVIDIA RTX 4090', name: 'NVIDIA RTX 4090', vramGb: 24, available: true },
      { id: 'NVIDIA RTX A6000', name: 'NVIDIA RTX A6000', vramGb: 48, available: true },
      { id: 'NVIDIA T4', name: 'NVIDIA T4', vramGb: 16, available: true },
      { id: 'custom', name: 'Custom (specify manually)', vramGb: 0, available: true },
    ];
  }

  async deploy(config: DeployConfig): Promise<ProviderDeployment> {
    if (!config.sshHost || !config.sshUsername) {
      throw new Error('SSH host and username are required for SSH Compose deployments');
    }

    const composeYaml = (config.artifactConfig as Record<string, unknown>)?.composeYaml as string;
    if (!composeYaml) {
      throw new Error('composeYaml is required in artifactConfig for SSH Compose deployments');
    }

    const composeProject = (config.artifactConfig as Record<string, unknown>)?.composeProject as string
      || `naap-${config.artifactType}-${Date.now()}`;
    const healthPort = config.healthPort || 9090;
    const healthEndpoint = config.healthEndpoint || '/health';

    // Connect via SSH
    const connectRes = await authenticatedProviderFetch(this.slug, this.apiConfig, '/connect', {
      method: 'POST',
      body: JSON.stringify({
        host: config.sshHost,
        port: config.sshPort || 22,
        username: config.sshUsername,
      }),
    });

    if (!connectRes.ok) {
      const error = await connectRes.text();
      throw new Error(`SSH connection failed: ${error}`);
    }

    // Generate deploy script that writes compose file and starts services
    const deployScript = this.buildDeployScript(composeProject, composeYaml, healthPort, healthEndpoint);

    const scriptRes = await authenticatedProviderFetch(this.slug, this.apiConfig, '/exec/script', {
      method: 'POST',
      body: JSON.stringify({
        host: config.sshHost,
        port: config.sshPort || 22,
        username: config.sshUsername,
        script: deployScript,
        timeout: 1800000,
        workingDirectory: '/tmp',
      }),
    });

    if (!scriptRes.ok) {
      const error = await scriptRes.text();
      throw new Error(`SSH compose deploy failed: ${error}`);
    }

    const scriptData = await scriptRes.json();
    const jobId = scriptData.data?.jobId || scriptData.jobId;

    return {
      providerDeploymentId: `compose:${config.sshHost}:${composeProject}:${jobId}:${healthPort}:${healthEndpoint}`,
      endpointUrl: `http://${config.sshHost}:${healthPort}`,
      status: 'DEPLOYING',
      metadata: {
        jobId,
        composeProject,
        sshHost: config.sshHost,
        healthPort,
        healthEndpoint,
      },
    };
  }

  async getStatus(providerDeploymentId: string): Promise<ProviderStatus> {
    const { host, jobId, healthPort } = this.parseDeploymentId(providerDeploymentId);

    if (jobId) {
      try {
        const res = await authenticatedProviderFetch(this.slug, this.apiConfig, `/jobs/${jobId}`);
        if (res.ok) {
          const data = await res.json();
          const jobStatus = data.data?.status || data.status;
          if (jobStatus === 'completed') {
            const exitCode = data.data?.exitCode ?? data.exitCode;
            return {
              status: exitCode === 0 ? 'ONLINE' : 'FAILED',
              endpointUrl: `http://${host}:${healthPort}`,
              metadata: data.data || data,
            };
          }
          if (jobStatus === 'failed' || jobStatus === 'timeout' || jobStatus === 'cancelled') {
            return { status: 'FAILED', metadata: data.data || data };
          }
          return { status: 'DEPLOYING', metadata: data.data || data };
        }
      } catch {
        // Fall through
      }
    }

    return { status: 'ONLINE', endpointUrl: `http://${host}:${healthPort}` };
  }

  async destroy(providerDeploymentId: string, metadata?: Record<string, unknown>): Promise<void> {
    const { host, composeProject } = this.parseDeploymentId(providerDeploymentId);
    const sshUsername = (metadata?.sshUsername as string) || 'deploy';

    const destroyScript = [
      '#!/bin/bash',
      'set -euo pipefail',
      `echo "=== Stopping compose project ${composeProject} ==="`,
      `if [ -f /opt/naap/${composeProject}/docker-compose.yml ]; then`,
      `  docker compose -p ${composeProject} -f /opt/naap/${composeProject}/docker-compose.yml down -v --remove-orphans`,
      `  rm -rf /opt/naap/${composeProject}`,
      `  echo "Compose project ${composeProject} destroyed"`,
      'else',
      `  echo "Compose file not found, attempting project-only cleanup"`,
      `  docker compose -p ${composeProject} down -v --remove-orphans 2>/dev/null || true`,
      'fi',
    ].join('\n');

    const res = await authenticatedProviderFetch(this.slug, this.apiConfig, '/exec/script', {
      method: 'POST',
      body: JSON.stringify({
        host,
        port: 22,
        username: sshUsername,
        script: destroyScript,
        timeout: 60000,
      }),
    });

    if (!res.ok && res.status !== 404) {
      const error = await res.text();
      throw new Error(`SSH compose destroy failed: ${error}`);
    }
  }

  async update(providerDeploymentId: string, config: UpdateConfig): Promise<ProviderDeployment> {
    const { host, composeProject, healthPort, healthEndpoint } = this.parseDeploymentId(providerDeploymentId);

    const newComposeYaml = (config.artifactConfig as Record<string, unknown>)?.composeYaml as string;

    const updateScript = [
      '#!/bin/bash',
      'set -euo pipefail',
      ...(newComposeYaml
        ? [
          `echo "=== Updating compose file ==="`,
          `cat > /opt/naap/${composeProject}/docker-compose.yml << 'COMPOSE_EOF'`,
          newComposeYaml,
          'COMPOSE_EOF',
          `chmod 600 /opt/naap/${composeProject}/docker-compose.yml`,
        ]
        : []),
      `echo "=== Pulling latest images ==="`,
      `docker compose -p ${composeProject} -f /opt/naap/${composeProject}/docker-compose.yml pull`,
      `echo "=== Restarting services ==="`,
      `docker compose -p ${composeProject} -f /opt/naap/${composeProject}/docker-compose.yml up -d --remove-orphans`,
      `echo "=== Waiting for health ==="`,
      'for i in $(seq 1 30); do',
      `  if curl -sf http://localhost:${healthPort}${healthEndpoint} > /dev/null 2>&1; then`,
      '    echo "Healthy after $((i * 10))s"',
      '    exit 0',
      '  fi',
      '  echo "Waiting... ($i/30)"',
      '  sleep 10',
      'done',
      'echo "Health check failed after update"',
      'exit 1',
    ].join('\n');

    const res = await authenticatedProviderFetch(this.slug, this.apiConfig, '/exec/script', {
      method: 'POST',
      body: JSON.stringify({
        host,
        port: 22,
        username: 'deploy',
        script: updateScript,
        timeout: 900000,
      }),
    });

    if (!res.ok) {
      const error = await res.text();
      throw new Error(`SSH compose update failed: ${error}`);
    }

    const data = await res.json();
    const jobId = data.data?.jobId || data.jobId;

    return {
      providerDeploymentId: `compose:${host}:${composeProject}:${jobId}:${healthPort}:${healthEndpoint}`,
      endpointUrl: `http://${host}:${healthPort}`,
      status: 'UPDATING',
      metadata: { jobId },
    };
  }

  async healthCheck(_providerDeploymentId: string, endpointUrl?: string): Promise<HealthResult> {
    if (!endpointUrl) {
      return { healthy: false, status: 'RED' };
    }

    const { host, healthPort, healthEndpoint } = this.parseDeploymentId(_providerDeploymentId);

    try {
      const start = Date.now();
      const res = await authenticatedProviderFetch(this.slug, this.apiConfig, '/exec', {
        method: 'POST',
        body: JSON.stringify({
          host,
          port: 22,
          username: 'deploy',
          command: `curl -sf -o /dev/null -w "%{http_code}" http://localhost:${healthPort}${healthEndpoint}`,
          timeout: 15000,
        }),
      });

      const responseTimeMs = Date.now() - start;

      if (!res.ok) {
        return { healthy: false, status: 'RED', responseTimeMs };
      }

      const data = await res.json();
      const exitCode = data.data?.exitCode ?? data.exitCode;
      const stdout = (data.data?.stdout || data.stdout || '').trim();
      const statusCode = parseInt(stdout, 10) || 0;
      const healthy = exitCode === 0 && statusCode >= 200 && statusCode < 300;

      return {
        healthy,
        status: healthy ? (responseTimeMs > 5000 ? 'ORANGE' : 'GREEN') : 'RED',
        responseTimeMs,
        statusCode,
        details: data.data || data,
      };
    } catch {
      return { healthy: false, status: 'RED' };
    }
  }

  private buildDeployScript(project: string, composeYaml: string, healthPort: number, healthEndpoint: string): string {
    return [
      '#!/bin/bash',
      'set -euo pipefail',
      '',
      'echo "=== Preflight checks ==="',
      'docker compose version || { echo "docker compose not found"; exit 1; }',
      '',
      `echo "=== Setting up compose project ${project} ==="`,
      `mkdir -p /opt/naap/${project}`,
      `chmod 700 /opt/naap/${project}`,
      '',
      `cat > /opt/naap/${project}/docker-compose.yml << 'COMPOSE_EOF'`,
      composeYaml,
      'COMPOSE_EOF',
      `chmod 600 /opt/naap/${project}/docker-compose.yml`,
      '',
      `echo "=== Starting compose project ==="`,
      `docker compose -p ${project} -f /opt/naap/${project}/docker-compose.yml pull`,
      `docker compose -p ${project} -f /opt/naap/${project}/docker-compose.yml up -d`,
      '',
      `echo "=== Waiting for health endpoint ==="`,
      'for i in $(seq 1 60); do',
      `  if curl -sf http://localhost:${healthPort}${healthEndpoint} > /dev/null 2>&1; then`,
      '    echo "Healthy after $((i * 10))s"',
      '    exit 0',
      '  fi',
      '  echo "Waiting... ($i/60)"',
      '  sleep 10',
      'done',
      'echo "=== FAILED: Services not healthy after 600s ==="',
      `docker compose -p ${project} -f /opt/naap/${project}/docker-compose.yml logs --tail 50`,
      'exit 1',
    ].join('\n');
  }

  private parseDeploymentId(providerDeploymentId: string): {
    host: string;
    composeProject: string;
    jobId: string;
    healthPort: string;
    healthEndpoint: string;
  } {
    // Format: compose:<host>:<project>:<jobId>:<healthPort>:<healthEndpoint>
    const parts = providerDeploymentId.split(':');
    // Skip the "compose" prefix
    const offset = parts[0] === 'compose' ? 1 : 0;
    return {
      host: parts[offset] || '',
      composeProject: parts[offset + 1] || '',
      jobId: parts[offset + 2] || '',
      healthPort: parts[offset + 3] || '9090',
      healthEndpoint: parts[offset + 4] || '/health',
    };
  }
}
