export const BUILT_IN_SKILLS = [
  {
    name: 'record-expense', description: 'Record a business or personal expense', category: 'bookkeeping',
    triggerPatterns: ['\\$\\d', 'spent ', 'paid ', 'bought ', 'purchased '],
    parameters: { amountCents: { type: 'number', required: true, extractHint: 'dollar amount times 100' }, vendor: { type: 'string', required: false, extractHint: 'business name' }, description: { type: 'string', required: false }, date: { type: 'date', required: false, default: 'today' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-expense/expenses' },
    responseTemplate: 'Recorded: {{amountFormatted}} — {{description}} [{{categoryName}}]',
  },
  {
    name: 'query-expenses', description: 'Query, search, list, or ask questions about expenses', category: 'bookkeeping',
    triggerPatterns: ['show.*expense', 'list.*expense', 'last \\d+ expense', 'how much.*spen', 'recent expense', 'summary.*expense'],
    parameters: { question: { type: 'string', required: true, extractHint: 'the full user message' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-expense/advisor/ask' },
  },
  {
    name: 'query-finance', description: 'Ask about cash balance, revenue, profit, tax, clients, or general financial questions', category: 'finance',
    triggerPatterns: ['balance', 'revenue', 'profit', 'loss', 'tax', 'client.*owe', 'outstanding', 'income', 'net '],
    parameters: { question: { type: 'string', required: true, extractHint: 'the full user message' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-core/ask' },
  },
  {
    name: 'scan-receipt', description: 'Scan and process a receipt photo', category: 'bookkeeping',
    triggerPatterns: [],
    parameters: { imageUrl: { type: 'string', required: true, extractHint: 'attachment URL' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-expense/receipts/ocr' },
  },
  {
    name: 'scan-document', description: 'Process a PDF document (receipt or statement)', category: 'bookkeeping',
    triggerPatterns: [],
    parameters: { imageUrl: { type: 'string', required: true, extractHint: 'attachment URL' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-expense/receipts/ocr' },
  },
  {
    name: 'create-invoice', description: 'Create an invoice for a client', category: 'invoicing',
    triggerPatterns: ['invoice .+ \\$'],
    parameters: { clientName: { type: 'string', required: true }, amountCents: { type: 'number', required: true }, description: { type: 'string', required: false, default: 'Services' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/invoices' },
  },
  {
    name: 'simulate-scenario', description: 'Run a what-if financial simulation', category: 'planning',
    triggerPatterns: ['what if', 'what.?if', 'simulate', 'scenario', 'hire.*\\$', 'lose.*client'],
    parameters: { scenario: { type: 'string', required: true, extractHint: 'the full user message' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-core/simulate' },
  },
  {
    name: 'proactive-alerts', description: 'Check for alerts, notifications, or things needing attention', category: 'insights',
    triggerPatterns: ['alert', 'notification', 'check.?up', 'anything.*know', 'what.?s new'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-expense/advisor/proactive-alerts', queryParams: [] },
  },
  {
    name: 'expense-breakdown', description: 'Show spending breakdown by category as a chart', category: 'insights',
    triggerPatterns: ['breakdown', 'categor.*chart', 'pie chart', 'bar chart', 'spending chart'],
    parameters: { chartType: { type: 'string', required: false, default: 'bar' } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-expense/advisor/chart', queryParams: ['startDate', 'endDate', 'chartType'] },
  },
  {
    name: 'categorize-expenses', description: 'Auto-categorize uncategorized expenses into the right expense categories', category: 'bookkeeping',
    triggerPatterns: ['categorize', 'classify', 'organize.*expense', 'fix.*categor', 'uncategorized', 'auto.?categor'],
    parameters: {},
    endpoint: { method: 'INTERNAL', url: '' },  // handled inline by agent brain
  },
  {
    name: 'edit-expense', description: 'Edit an existing expense — change amount, category, vendor, date, or description', category: 'bookkeeping',
    triggerPatterns: ['change.*expense', 'edit.*expense', 'update.*expense', 'fix.*expense', 'correct.*expense'],
    parameters: { expenseId: { type: 'string', required: false, extractHint: 'expense ID or "last"' } },
    endpoint: { method: 'PUT', url: '/api/v1/agentbook-expense/expenses/:id' },
    confirmBefore: true,
  },
  {
    name: 'split-expense', description: 'Split an expense into business and personal portions', category: 'bookkeeping',
    triggerPatterns: ['split.*expense', 'part.*business.*personal', 'half.*personal'],
    parameters: { expenseId: { type: 'string', required: false }, businessPercent: { type: 'number', required: false, default: 50 } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-expense/expenses/:id/split' },
    confirmBefore: true,
  },
  {
    name: 'review-queue', description: 'Show expenses that need human review — low confidence, pending, or flagged', category: 'bookkeeping',
    triggerPatterns: ['review', 'pending.*review', 'need.*attention', 'flagged'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-expense/review-queue' },
  },
  {
    name: 'manage-recurring', description: 'View or manage recurring expense patterns — subscriptions, rent, monthly charges', category: 'bookkeeping',
    triggerPatterns: ['recurring', 'subscription', 'monthly.*expense', 'regular.*payment'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-expense/recurring-suggestions' },
  },
  {
    name: 'vendor-insights', description: 'Show spending patterns by vendor — who you spend most with, trends', category: 'insights',
    triggerPatterns: ['vendor.*spend', 'who.*spend.*most', 'top.*vendor', 'vendor.*pattern'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-expense/vendors' },
  },
  {
    name: 'query-invoices', description: 'List, search, or ask about invoices — outstanding, overdue, by client, by status', category: 'invoicing',
    triggerPatterns: ['show.*invoice', 'list.*invoice', 'outstanding.*invoice', 'unpaid.*invoice', 'overdue.*invoice', 'invoice.*status', 'my invoice'],
    parameters: { status: { type: 'string', required: false }, clientName: { type: 'string', required: false } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-invoice/invoices', queryParams: ['status', 'clientId', 'limit'] },
  },
  {
    name: 'aging-report', description: 'Show accounts receivable aging — who owes money and how overdue', category: 'invoicing',
    triggerPatterns: ['aging', 'who.*owe', 'accounts.*receivable', 'ar report', 'overdue.*client', 'owe.*money'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-invoice/aging-report' },
  },
  {
    name: 'query-estimates', description: 'List estimates — pending, approved, converted', category: 'invoicing',
    triggerPatterns: ['show.*estimate', 'list.*estimate', 'pending.*estimate', 'my estimate'],
    parameters: { status: { type: 'string', required: false } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-invoice/estimates', queryParams: ['status', 'clientId'] },
  },
  {
    name: 'query-clients', description: 'List clients or show client details — billing history, outstanding balance', category: 'invoicing',
    triggerPatterns: ['show.*client', 'list.*client', 'client.*detail', 'client.*balance', 'my client'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-invoice/clients' },
  },
  {
    name: 'timer-status', description: 'Check if a time tracking timer is running and how long', category: 'invoicing',
    triggerPatterns: ['timer.*status', 'timer.*running', 'is.*timer', 'how long.*timer'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-invoice/timer/status' },
  },
  {
    name: 'unbilled-summary', description: 'Show unbilled time by client — hours logged but not yet invoiced', category: 'invoicing',
    triggerPatterns: ['unbilled', 'not.*invoiced', 'billable.*time', 'hours.*not.*billed'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-invoice/unbilled-summary' },
  },
  {
    name: 'send-invoice', description: 'Send a draft or created invoice to the client via email', category: 'invoicing',
    triggerPatterns: ['send.*invoice', 'email.*invoice', 'deliver.*invoice', 'send.*that.*invoice'],
    parameters: { invoiceId: { type: 'string', required: false, extractHint: 'invoice ID, number like INV-YYYY-NNNN, or "last"' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/invoices/:id/send' },
    confirmBefore: true,
  },
  {
    name: 'record-payment', description: 'Record a payment received for an invoice', category: 'invoicing',
    triggerPatterns: ['got.*paid', 'received.*payment', 'record.*payment', 'got.*\\$.*from', 'payment.*received'],
    parameters: { invoiceId: { type: 'string', required: false }, amountCents: { type: 'number', required: false }, clientName: { type: 'string', required: false }, method: { type: 'string', required: false, default: 'manual' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/payments' },
    confirmBefore: true,
  },
  {
    name: 'create-estimate', description: 'Create a project estimate or quote for a client', category: 'invoicing',
    triggerPatterns: ['estimate.*\\$', 'quote.*\\$', 'proposal.*\\$', 'create.*estimate'],
    parameters: { clientName: { type: 'string', required: true }, amountCents: { type: 'number', required: true }, description: { type: 'string', required: true } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/estimates' },
  },
  {
    name: 'start-timer', description: 'Start a time tracking timer for a project or client', category: 'invoicing',
    triggerPatterns: ['start.*timer', 'track.*time', 'clock.*in', 'begin.*timer'],
    parameters: { description: { type: 'string', required: false }, clientName: { type: 'string', required: false }, projectName: { type: 'string', required: false } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/timer/start' },
  },
  {
    name: 'stop-timer', description: 'Stop the running time tracker', category: 'invoicing',
    triggerPatterns: ['stop.*timer', 'clock.*out', 'end.*timer', 'pause.*timer'],
    parameters: {},
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/timer/stop' },
  },
  {
    name: 'send-reminder', description: 'Send payment reminder for overdue invoices', category: 'invoicing',
    triggerPatterns: ['send.*remind', 'remind.*overdue', 'follow.*up.*invoice', 'chase.*payment', 'nudge.*client', 'remind.*payment'],
    parameters: { invoiceId: { type: 'string', required: false, extractHint: 'invoice ID or "all" for all overdue' } },
    endpoint: { method: 'INTERNAL', url: '' },
  },
  {
    name: 'tax-estimate', description: 'Show tax estimate — income tax, self-employment tax, effective rate', category: 'tax',
    triggerPatterns: ['tax.*estimate', 'how much.*tax', 'tax.*owe', 'tax.*situation', 'tax.*liability'],
    parameters: { period: { type: 'string', required: false, default: 'ytd' } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax/estimate', queryParams: ['startDate', 'endDate'] },
  },
  {
    name: 'quarterly-payments', description: 'Show quarterly tax payment schedule and status', category: 'tax',
    triggerPatterns: ['quarterly.*payment', 'quarterly.*tax', 'estimated.*payment', 'quarterly.*due'],
    parameters: { year: { type: 'string', required: false } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax/quarterly', queryParams: ['year'] },
  },
  {
    name: 'tax-deductions', description: 'Show potential tax deductions and savings opportunities', category: 'tax',
    triggerPatterns: ['deduction', 'tax.*saving', 'write.*off', 'deductible', 'tax.*break'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax/deductions' },
  },
  {
    name: 'pnl-report', description: 'Show profit & loss report — revenue, expenses, net income', category: 'tax',
    triggerPatterns: ['p.?&?.?l', 'profit.*loss', 'income.*statement', 'net.*income', 'how.*much.*profit'],
    parameters: { startDate: { type: 'string', required: false }, endDate: { type: 'string', required: false } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/reports/pnl', queryParams: ['startDate', 'endDate'] },
  },
  {
    name: 'balance-sheet', description: 'Show balance sheet — assets, liabilities, equity', category: 'tax',
    triggerPatterns: ['balance.*sheet', 'asset.*liabilit', 'net.*worth', 'equity'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/reports/balance-sheet', queryParams: ['asOfDate'] },
  },
  {
    name: 'cashflow-report', description: 'Show cash flow statement or projection — inflows, outflows, runway', category: 'tax',
    triggerPatterns: ['cash.*flow', 'cash.*projection', 'runway', 'burn.*rate', 'how long.*cash.*last'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/cashflow/projection' },
  },
  {
    name: 'financial-snapshot', description: 'Quick financial summary — cash, revenue, expenses, profit at a glance', category: 'finance',
    triggerPatterns: ['financial.*summary', 'financial.*snapshot', 'overview', 'dashboard', 'how.*doing.*financially', 'financial.*health'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-core/financial-snapshot' },
  },
  {
    name: 'money-moves', description: 'Proactive money moves and action items — things you should do with your money', category: 'finance',
    triggerPatterns: ['money.*move', 'action.*item', 'what.*should.*do', 'suggestion', 'recommend', 'advice.*money'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-core/money-moves' },
  },
  {
    name: 'bank-reconciliation', description: 'Check bank reconciliation status — matched vs unmatched transactions', category: 'bookkeeping',
    triggerPatterns: ['reconcil', 'unmatched.*transaction', 'bank.*match', 'bank.*status'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-expense/reconciliation-summary' },
  },
  {
    name: 'cpa-notes', description: 'Add or view notes for CPA/accountant — tax questions, review items', category: 'finance',
    triggerPatterns: ['cpa.*note', 'accountant.*note', 'note.*cpa', 'note.*accountant', 'tell.*cpa', 'ask.*cpa'],
    parameters: { note: { type: 'string', required: false, extractHint: 'the note content' } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-core/cpa/notes' },
  },
  {
    name: 'cpa-share', description: 'Generate a secure access link to share financial data with CPA/accountant', category: 'finance',
    triggerPatterns: ['share.*cpa', 'share.*accountant', 'cpa.*access', 'cpa.*link', 'give.*cpa.*access'],
    parameters: {},
    endpoint: { method: 'POST', url: '/api/v1/agentbook-core/cpa/generate-link' },
  },
  {
    name: 'create-automation', description: 'Create an automation rule from natural language — triggers, conditions, actions', category: 'finance',
    triggerPatterns: ['automat', 'when.*then', 'alert.*when', 'notify.*when', 'rule.*when'],
    parameters: { description: { type: 'string', required: true, extractHint: 'natural language rule description' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-core/automations/from-description' },
  },
  {
    name: 'list-automations', description: 'Show active automation rules', category: 'finance',
    triggerPatterns: ['show.*automat', 'list.*automat', 'my.*automat', 'active.*rule'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-core/automations' },
  },
  {
    name: 'tax-filing-start', description: 'Start tax filing — create filing session, auto-populate from books, identify missing fields', category: 'tax',
    triggerPatterns: ['start.*tax.*fil', 'file.*my.*tax', 'begin.*return', 'prepare.*tax.*return', 'tax.*return'],
    parameters: { taxYear: { type: 'number', required: false, default: 2025 } },
    endpoint: { method: 'INTERNAL', url: '' },
  },
  {
    name: 'tax-filing-status', description: 'Check tax filing progress — completeness by form, what is missing', category: 'tax',
    triggerPatterns: ['tax.*filing.*status', 'filing.*progress', 'what.*missing.*tax', 'tax.*complete', 'filing.*complete'],
    parameters: { taxYear: { type: 'number', required: false, default: 2025 } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax-filing/2025' },
  },
  {
    name: 'tax-slip-scan', description: 'Upload and scan a tax slip (T4, T5, RRSP, TFSA, bank statement) for OCR extraction', category: 'tax',
    triggerPatterns: ['upload.*slip', 'scan.*t4', 'scan.*t5', 'scan.*rrsp', 'scan.*slip', 'tax.*document'],
    parameters: { imageUrl: { type: 'string', required: false } },
    endpoint: { method: 'INTERNAL', url: '' },
  },
  {
    name: 'tax-slip-list', description: 'Show uploaded tax slips and their status', category: 'tax',
    triggerPatterns: ['show.*slip', 'list.*slip', 'uploaded.*slip', 'my.*slip', 'tax.*slip'],
    parameters: { taxYear: { type: 'number', required: false, default: 2025 } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax-slips', queryParams: ['taxYear'] },
  },
  {
    name: 'ca-t2125-review', description: 'Review T2125 Statement of Business Income — revenue, expenses, vehicle, home office', category: 'tax',
    triggerPatterns: ['review.*t2125', 'business.*income.*form', 't2125', 'statement.*business'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax-filing/2025' },
  },
  {
    name: 'ca-t1-review', description: 'Review T1 General personal income tax return — income sources, deductions, credits', category: 'tax',
    triggerPatterns: ['review.*t1', 'personal.*return', 't1.*general', 't1.*review'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax-filing/2025' },
  },
  {
    name: 'ca-gst-hst-review', description: 'Review GST/HST return — collected tax, input tax credits, net tax', category: 'tax',
    triggerPatterns: ['review.*gst', 'review.*hst', 'sales.*tax.*return', 'gst.*hst.*review', 'gst.*return'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax-filing/2025' },
  },
  {
    name: 'ca-schedule-1-review', description: 'Review Schedule 1 federal tax calculation', category: 'tax',
    triggerPatterns: ['schedule.*1', 'federal.*tax.*calc'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax-filing/2025' },
  },
  {
    name: 'tax-filing-field', description: 'Provide a value for a missing tax filing field', category: 'tax',
    triggerPatterns: [],
    parameters: { formCode: { type: 'string', required: true }, fieldId: { type: 'string', required: true }, value: { type: 'string', required: true } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-tax/tax-filing/2025/field' },
  },
  {
    name: 'tax-filing-validate', description: 'Run validation rules on tax return — check for errors before filing', category: 'tax',
    triggerPatterns: ['validate.*tax', 'check.*tax.*error', 'verify.*return', 'tax.*ready.*file', 'any.*error.*tax'],
    parameters: { taxYear: { type: 'number', required: false, default: 2025 } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-tax/tax-filing/2025/validate' },
  },
  {
    name: 'tax-filing-export', description: 'Generate and export tax forms — PDF or JSON format', category: 'tax',
    triggerPatterns: ['export.*tax', 'generate.*tax.*form', 'download.*return', 'create.*tax.*file', 'print.*tax', 'pdf.*tax'],
    parameters: { format: { type: 'string', required: false, default: 'json' } },
    endpoint: { method: 'INTERNAL', url: '' },
  },
  {
    name: 'tax-filing-submit', description: 'Submit tax return to CRA via certified partner API — e-file your return', category: 'tax',
    triggerPatterns: ['submit.*tax', 'submit.*cra', 'efile', 'netfile', 'submit.*return', 'file.*return.*cra', 'send.*cra'],
    parameters: { taxYear: { type: 'number', required: false, default: 2025 } },
    endpoint: { method: 'INTERNAL', url: '' },
    confirmBefore: true,
  },
  {
    name: 'tax-filing-check', description: 'Check e-filing status — accepted, rejected, or pending by CRA', category: 'tax',
    triggerPatterns: ['filing.*status.*cra', 'cra.*accept', 'return.*status.*cra', 'check.*filing.*status', 'did.*cra.*accept'],
    parameters: { taxYear: { type: 'number', required: false, default: 2025 } },
    endpoint: { method: 'GET', url: '/api/v1/agentbook-tax/tax-filing/2025/status' },
  },
  {
    name: 'telegram-setup', description: 'Configure Telegram bot — connect your own bot by providing the API token from @BotFather', category: 'finance',
    triggerPatterns: ['setup.*telegram', 'connect.*telegram', 'telegram.*bot.*token', 'configure.*telegram', 'my.*bot.*token'],
    parameters: { botToken: { type: 'string', required: false, extractHint: 'Telegram bot API token from @BotFather' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-core/telegram/setup' },
  },
  {
    name: 'telegram-status', description: 'Check Telegram bot connection status', category: 'finance',
    triggerPatterns: ['telegram.*status', 'bot.*connected', 'telegram.*config'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-core/telegram/status' },
  },
  {
    name: 'convert-estimate', description: 'Convert an approved estimate into an invoice', category: 'invoicing',
    triggerPatterns: ['convert.*estimate', 'estimate.*invoice', 'turn.*estimate.*invoice'],
    parameters: { estimateId: { type: 'string', required: false, extractHint: 'estimate ID or "last"' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/estimates/:id/convert' },
  },
  {
    name: 'void-invoice', description: 'Void/cancel an invoice — reverses journal entries', category: 'invoicing',
    triggerPatterns: ['void.*invoice', 'cancel.*invoice', 'delete.*invoice'],
    parameters: { invoiceId: { type: 'string', required: false, extractHint: 'invoice ID, number, or "last"' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/invoices/:id/void' },
    confirmBefore: true,
  },
  {
    name: 'create-credit-note', description: 'Issue a credit note against an invoice — partial refund or adjustment', category: 'invoicing',
    triggerPatterns: ['credit.*note', 'credit.*invoice', 'issue.*credit', 'refund.*invoice'],
    parameters: { invoiceId: { type: 'string', required: false }, amountCents: { type: 'number', required: false }, reason: { type: 'string', required: false } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/credit-notes' },
    confirmBefore: true,
  },
  {
    name: 'create-payment-link', description: 'Generate a Stripe payment link for an invoice so clients can pay online', category: 'invoicing',
    triggerPatterns: ['payment.*link', 'pay.*link', 'stripe.*link', 'online.*pay', 'pay.*online', 'generate.*link'],
    parameters: { invoiceId: { type: 'string', required: false } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-invoice/invoices/:id/payment-link' },
  },
  {
    name: 'toggle-auto-reminders', description: 'Enable or disable automatic payment reminders for overdue invoices', category: 'invoicing',
    triggerPatterns: ['auto.*remind', 'automatic.*remind', 'enable.*remind', 'disable.*remind'],
    parameters: { enabled: { type: 'boolean', required: false } },
    endpoint: { method: 'PUT', url: '/api/v1/agentbook-core/tenant-config' },
  },
  {
    name: 'set-budget', description: 'Set a monthly budget — total or per category', category: 'bookkeeping',
    triggerPatterns: ['set.*budget', 'budget.*\\$', 'monthly.*budget', 'spending.*limit'],
    parameters: { amountCents: { type: 'number', required: true }, category: { type: 'string', required: false }, period: { type: 'string', required: false, default: 'monthly' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-expense/budgets' },
  },
  {
    name: 'query-budget', description: 'Check budget status — spending vs budget by category', category: 'bookkeeping',
    triggerPatterns: ['budget.*status', 'over.*budget', 'under.*budget', 'how.*budget', 'spending.*vs.*budget', 'check.*budget'],
    parameters: {},
    endpoint: { method: 'GET', url: '/api/v1/agentbook-expense/budgets/status' },
  },
  {
    name: 'expense-report', description: 'Generate an expense report for a date range', category: 'bookkeeping',
    triggerPatterns: ['expense.*report', 'generate.*report', 'expense.*pdf', 'print.*expense', 'download.*expense'],
    parameters: { startDate: { type: 'string', required: false }, endDate: { type: 'string', required: false } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-expense/reports/expense-pdf' },
  },
  {
    name: 'general-question', description: 'Answer any general financial or accounting question', category: 'finance',
    triggerPatterns: [],
    parameters: { question: { type: 'string', required: true, extractHint: 'the full user message' } },
    endpoint: { method: 'POST', url: '/api/v1/agentbook-core/ask' },
  },
];
